sudo: required
dist: trusty
language: go
env:
  global:
    - WEBSERVICE_VERSION="1.3.0-rc.0"
  matrix:
    - RUN_PROD=false
    - RUN_PROD=true

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get -u github.com/NYTimes/openapi2proto/cmd/openapi2proto


