sudo: required
dist: trusty
language: python
python:
- 2.7.12
env:
  global:
  - WEBSERVICE_VERSION="1.3.0-rc.0"
  - PROTOFILE="trs.proto"
  - SWAGGERFILE="ga4gh-tool-discovery.yaml"
addons:
  apt:
    packages:
    - golang-go
    - unzip
install:
- wget https://raw.githubusercontent.com/ga4gh/tool-registry-schemas/feature/trsv_changes/src/main/resources/swagger/ga4gh-tool-discovery.yaml
- go get -u github.com/NYTimes/openapi2proto/cmd/openapi2proto
- go get -u github.com/golang/protobuf/protoc-gen-go
- python --version
- pip list
- go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
- go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
- export PROTOC_ZIP=protoc-3.3.0-linux-x86_64.zip
- curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOC_ZIP
- sudo unzip -o $PROTOC_ZIP -d /usr/local
- rm -f $PROTOC_ZIP
- wget https://raw.githubusercontent.com/ga4gh/tool-registry-validator/feature/flask/validator/compareSwaggerYaml.py
script:
- sed -e 's/GA4GH Tool Discovery API/trs/g' -i $SWAGGERFILE
- openapi2proto -spec $SWAGGERFILE -options > $PROTOFILE
- sed -i '/package trs;/d' $PROTOFILE
- sed -e s/trsService/trs/g -i $PROTOFILE
- protoc -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis
  --swagger_out=logtostderr=true:. $PROTOFILE
- pip install ruamel.yaml
- python compareSwaggerYaml.py $SWAGGERFILE trs.swagger.json
before_install:
- openssl aes-256-cbc -K $encrypted_1c6d8bbd9c6b_key -iv $encrypted_1c6d8bbd9c6b_iv
  -in github_deploy_key.enc -out github_deploy_key -d
