sudo: required
dist: trusty
language: go
python: 
  - "2.7.12"
env:
  global:
    - WEBSERVICE_VERSION="1.3.0-rc.0"
    - PROTOFILE="trs.proto"
    - SWAGGERFILE="ga4gh-tool-discovery.yaml"

install:
  # Add Godeps dependencies to GOPATH and PATH
  - go get -u github.com/NYTimes/openapi2proto/cmd/openapi2proto
  - python --version
  - sudo apt-get install unzip python python-pip
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - python --version
  - pip list
  - pip install ruamel.yaml
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - export PROTOC_ZIP=protoc-3.5.0-linux-x86_64.zip
  - curl -OL https://github.com/google/protobuf/releases/download/v3.5.0/$PROTOC_ZIP
  - sudo unzip -o $PROTOC_ZIP -d /usr/local
  - rm -f $PROTOC_ZIP
  - wget https://raw.githubusercontent.com/ga4gh/tool-registry-validator/feature/flask/validator/compareSwaggerYaml.py


script:
  - sed -e 's/GA4GH Tool Discovery API/trs/g' -i $SWAGGERFILE
  - openapi2proto -spec $SWAGGERFILE -options > $PROTOFILE
  - sed -i '/package trs;/d' $PROTOFILE
  - sed -e s/trsService/trs/g -i $PROTOFILE
  - protoc -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --swagger_out=logtostderr=true:. $PROTOFILE
  - python compareSwaggerYaml.py $SWAGGERFILE trs.swagger.json

